import { type NextRequest, NextResponse } from "next/server"
import { createServerClient } from "@supabase/ssr"
import { cookies } from "next/headers"

export const maxDuration = 30

export async function POST(request: NextRequest) {
  try {
    const cookieStore = await cookies()
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll()
          },
          setAll(cookiesToSet) {
            cookiesToSet.forEach(({ name, value, options }) => {
              cookieStore.set(name, value, options)
            })
          },
        },
      },
    )

    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { format, strategy } = await request.json()

    if (format === "pdf") {
      // Generate PDF content
      const pdfContent = generatePDFContent(strategy)
      return new NextResponse(pdfContent, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${strategy.title.replace(/\s+/g, "_")}_Strategy.pdf"`,
        },
      })
    }

    if (format === "docx") {
      // Generate DOCX content (simplified HTML for now)
      const htmlContent = generateHTMLDocument(strategy)
      return new NextResponse(htmlContent, {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${strategy.title.replace(/\s+/g, "_")}_Strategy.docx"`,
        },
      })
    }

    return NextResponse.json({ error: "Invalid format" }, { status: 400 })
  } catch (error) {
    console.error("Export error:", error)
    return NextResponse.json({ error: "Export failed" }, { status: 500 })
  }
}

function generatePDFContent(strategy: any): string {
  // For a real implementation, you'd use a library like jsPDF or puppeteer
  // This is a simplified text representation
  const content = strategy.content || {}
  let text = `TENDER BID STRATEGY\n${"=".repeat(50)}\n\n`
  text += `Title: ${strategy.title}\n\n`

  if (strategy.summary) {
    text += `SUMMARY\n${"-".repeat(30)}\n${strategy.summary}\n\n`
  }

  Object.entries(content).forEach(([key, value]) => {
    if (value && key !== "raw") {
      text += `${key.toUpperCase().replace(/_/g, " ")}\n${"-".repeat(30)}\n${value}\n\n`
    }
  })

  text += `\nGenerated by BidMate AI Strategist\nDate: ${new Date().toLocaleDateString()}`
  return text
}

function generateHTMLDocument(strategy: any): string {
  const content = strategy.content || {}
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${strategy.title} - Bid Strategy</title>
  <style>
    body { font-family: 'Calibri', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #111827; line-height: 1.6; }
    h1 { color: #005B8F; border-bottom: 3px solid #19A7CE; padding-bottom: 15px; font-size: 28px; }
    h2 { color: #005B8F; margin-top: 30px; font-size: 18px; border-left: 4px solid #19A7CE; padding-left: 12px; }
    .summary { background: #F7F9FC; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #19A7CE; }
    .section { margin-bottom: 25px; }
    .section p { color: #374151; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #E5E7EB; font-size: 12px; color: #6B7280; text-align: center; }
    .logo { color: #005B8F; font-weight: bold; }
  </style>
</head>
<body>
  <h1>${strategy.title}</h1>
  ${strategy.summary ? `<div class="summary"><strong>Executive Summary:</strong><br/>${strategy.summary}</div>` : ""}
  ${Object.entries(content)
    .filter(([key, value]) => value && key !== "raw")
    .map(
      ([key, value]) => `
    <div class="section">
      <h2>${key.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase())}</h2>
      <p>${String(value).replace(/\n/g, "<br/>")}</p>
    </div>
  `,
    )
    .join("")}
  <div class="footer">
    <span class="logo">BidMate</span> AI Tender Strategist<br/>
    Generated on ${new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body>
</html>`
}
